language: swift
osx_image: xcode12
xcode_project: quick-questions.xcodeproj
xcode_scheme: quick-questions
xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 11

install:
  - ./install_swiftlint.sh

script:
  - swiftlint
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
